// Representative zip codes for each US state — used to query Brandify for nearby TJ's stores
export const STATE_ZIPS: Record<string, { zip: string; city: string }> = {
  AL: { zip: '35203', city: 'Birmingham' },
  AK: { zip: '99501', city: 'Anchorage' },
  AZ: { zip: '85004', city: 'Phoenix' },
  AR: { zip: '72201', city: 'Little Rock' },
  CA: { zip: '90001', city: 'Los Angeles' },
  CO: { zip: '80203', city: 'Denver' },
  CT: { zip: '06103', city: 'Hartford' },
  DE: { zip: '19801', city: 'Wilmington' },
  FL: { zip: '33101', city: 'Miami' },
  GA: { zip: '30303', city: 'Atlanta' },
  HI: { zip: '96813', city: 'Honolulu' },
  ID: { zip: '83702', city: 'Boise' },
  IL: { zip: '60601', city: 'Chicago' },
  IN: { zip: '46204', city: 'Indianapolis' },
  IA: { zip: '50309', city: 'Des Moines' },
  KS: { zip: '66101', city: 'Kansas City' },
  KY: { zip: '40202', city: 'Louisville' },
  LA: { zip: '70112', city: 'New Orleans' },
  ME: { zip: '04101', city: 'Portland' },
  MD: { zip: '21201', city: 'Baltimore' },
  MA: { zip: '02108', city: 'Boston' },
  MI: { zip: '48201', city: 'Detroit' },
  MN: { zip: '55401', city: 'Minneapolis' },
  MS: { zip: '39201', city: 'Jackson' },
  MO: { zip: '64101', city: 'Kansas City' },
  MT: { zip: '59601', city: 'Helena' },
  NE: { zip: '68102', city: 'Omaha' },
  NV: { zip: '89101', city: 'Las Vegas' },
  NH: { zip: '03101', city: 'Manchester' },
  NJ: { zip: '07102', city: 'Newark' },
  NM: { zip: '87102', city: 'Albuquerque' },
  NY: { zip: '10001', city: 'New York City' },
  NC: { zip: '27601', city: 'Raleigh' },
  ND: { zip: '58501', city: 'Bismarck' },
  OH: { zip: '44113', city: 'Cleveland' },
  OK: { zip: '73102', city: 'Oklahoma City' },
  OR: { zip: '97201', city: 'Portland' },
  PA: { zip: '19102', city: 'Philadelphia' },
  RI: { zip: '02903', city: 'Providence' },
  SC: { zip: '29201', city: 'Columbia' },
  SD: { zip: '57501', city: 'Pierre' },
  TN: { zip: '37201', city: 'Nashville' },
  TX: { zip: '73301', city: 'Austin' },
  UT: { zip: '84111', city: 'Salt Lake City' },
  VT: { zip: '05401', city: 'Burlington' },
  VA: { zip: '23219', city: 'Richmond' },
  WA: { zip: '98101', city: 'Seattle' },
  WV: { zip: '25301', city: 'Charleston' },
  WI: { zip: '53202', city: 'Milwaukee' },
  WY: { zip: '82001', city: 'Cheyenne' },
  DC: { zip: '20001', city: 'Washington D.C.' },
}

export const STATE_NAMES: Record<string, string> = {
  AL: 'Alabama', AK: 'Alaska', AZ: 'Arizona', AR: 'Arkansas', CA: 'California',
  CO: 'Colorado', CT: 'Connecticut', DE: 'Delaware', FL: 'Florida', GA: 'Georgia',
  HI: 'Hawaii', ID: 'Idaho', IL: 'Illinois', IN: 'Indiana', IA: 'Iowa',
  KS: 'Kansas', KY: 'Kentucky', LA: 'Louisiana', ME: 'Maine', MD: 'Maryland',
  MA: 'Massachusetts', MI: 'Michigan', MN: 'Minnesota', MS: 'Mississippi', MO: 'Missouri',
  MT: 'Montana', NE: 'Nebraska', NV: 'Nevada', NH: 'New Hampshire', NJ: 'New Jersey',
  NM: 'New Mexico', NY: 'New York', NC: 'North Carolina', ND: 'North Dakota', OH: 'Ohio',
  OK: 'Oklahoma', OR: 'Oregon', PA: 'Pennsylvania', RI: 'Rhode Island', SC: 'South Carolina',
  SD: 'South Dakota', TN: 'Tennessee', TX: 'Texas', UT: 'Utah', VT: 'Vermont',
  VA: 'Virginia', WA: 'Washington', WV: 'West Virginia', WI: 'Wisconsin', WY: 'Wyoming',
  DC: 'Washington D.C.',
}
